import type { Recipe } from "./types";

function img(seed: string): string {
  return `https://picsum.photos/seed/${seed}/800/600`;
}

export const SEED_RECIPES: Recipe[] = [
  {
    id: "recipe-1",
    title: "Classic Margherita Pizza",
    photoUrl: img("margherita-pizza"),
    category: "Dinner",
    description:
      "A simple, classic Neapolitan-style pizza with fresh mozzarella, basil, and San Marzano tomatoes.",
    ingredients: [
      { id: "i1", name: "Pizza Dough", quantity: 1, unit: "ball", category: "pantry" },
      { id: "i2", name: "San Marzano Tomatoes", quantity: 1, unit: "cup", category: "produce" },
      { id: "i3", name: "Fresh Mozzarella", quantity: 8, unit: "oz", category: "dairy" },
      { id: "i4", name: "Fresh Basil", quantity: 10, unit: "leaves", category: "produce" },
      { id: "i5", name: "Olive Oil", quantity: 2, unit: "tbsp", category: "pantry" },
      { id: "i6", name: "Salt", quantity: 1, unit: "tsp", category: "spices" },
    ],
    steps: [
      "Preheat oven to 500°F (260°C) with a pizza stone inside for 45 minutes.",
      "Stretch the pizza dough into a 12-inch round on a floured surface.",
      "Spread crushed San Marzano tomatoes evenly over the dough, leaving a border for the crust.",
      "Tear the fresh mozzarella into pieces and distribute over the sauce.",
      "Drizzle with olive oil and season lightly with salt.",
      "Slide onto the hot stone and bake for 8-10 minutes until the crust is golden and blistered.",
      "Remove, top with fresh basil leaves, slice, and serve immediately.",
    ],
    tags: ["italian", "vegetarian", "baking"],
    prepTimeMinutes: 20,
    cookTimeMinutes: 10,
    servings: 4,
    difficulty: "Medium",
    nutritionPerServing: {
      calories: 320,
      proteinG: 14,
      carbsG: 38,
      fatG: 12,
      fiberG: 2,
      sugarG: 3,
      sodiumMg: 540,
    },
    isFavorite: false,
    rating: 0,
    notes: "",
    createdAt: new Date("2026-01-05").toISOString(),
  },
  {
    id: "recipe-2",
    title: "Creamy Chicken Alfredo",
    photoUrl: img("chicken-alfredo"),
    category: "Dinner",
    description: "Rich and creamy fettuccine alfredo tossed with tender pan-seared chicken breast.",
    ingredients: [
      { id: "i1", name: "Fettuccine Pasta", quantity: 12, unit: "oz", category: "pantry" },
      { id: "i2", name: "Chicken Breast", quantity: 1, unit: "lb", category: "meat" },
      { id: "i3", name: "Heavy Cream", quantity: 1.5, unit: "cup", category: "dairy" },
      { id: "i4", name: "Parmesan Cheese", quantity: 1, unit: "cup", category: "dairy" },
      { id: "i5", name: "Butter", quantity: 3, unit: "tbsp", category: "dairy" },
      { id: "i6", name: "Garlic", quantity: 3, unit: "cloves", category: "produce" },
      { id: "i7", name: "Black Pepper", quantity: 0.5, unit: "tsp", category: "spices" },
    ],
    steps: [
      "Cook fettuccine in salted boiling water according to package instructions; drain, reserving 1/2 cup pasta water.",
      "Season chicken breast with salt and pepper, then sear in a hot pan with butter until golden and cooked through, about 6-7 minutes per side.",
      "Remove chicken, slice, and set aside.",
      "In the same pan, sauté minced garlic for 30 seconds, then add heavy cream and simmer for 3 minutes.",
      "Whisk in parmesan cheese until the sauce is smooth and thickened.",
      "Toss the cooked pasta in the sauce, adding reserved pasta water as needed to loosen.",
      "Top with sliced chicken and extra black pepper before serving.",
    ],
    tags: ["pasta", "comfort food"],
    prepTimeMinutes: 15,
    cookTimeMinutes: 25,
    servings: 4,
    difficulty: "Medium",
    nutritionPerServing: {
      calories: 610,
      proteinG: 38,
      carbsG: 45,
      fatG: 30,
      fiberG: 2,
      sugarG: 2,
      sodiumMg: 420,
    },
    isFavorite: false,
    rating: 0,
    notes: "",
    createdAt: new Date("2026-01-08").toISOString(),
  },
  {
    id: "recipe-3",
    title: "Avocado Toast with Poached Egg",
    photoUrl: img("avocado-toast"),
    category: "Breakfast",
    description: "A bright, protein-packed breakfast with creamy avocado and a perfectly poached egg.",
    ingredients: [
      { id: "i1", name: "Sourdough Bread", quantity: 2, unit: "slices", category: "pantry" },
      { id: "i2", name: "Avocado", quantity: 1, unit: "whole", category: "produce" },
      { id: "i3", name: "Eggs", quantity: 2, unit: "whole", category: "dairy" },
      { id: "i4", name: "Lemon Juice", quantity: 1, unit: "tsp", category: "produce" },
      { id: "i5", name: "Red Pepper Flakes", quantity: 0.25, unit: "tsp", category: "spices" },
      { id: "i6", name: "Salt", quantity: 0.5, unit: "tsp", category: "spices" },
    ],
    steps: [
      "Toast the sourdough slices until golden and crisp.",
      "Mash the avocado with lemon juice and salt in a bowl.",
      "Bring a pot of water to a gentle simmer, add a splash of vinegar, and poach the eggs for 3 minutes each.",
      "Spread the mashed avocado onto the toast.",
      "Top each slice with a poached egg and sprinkle with red pepper flakes.",
    ],
    tags: ["vegetarian", "quick", "healthy"],
    prepTimeMinutes: 10,
    cookTimeMinutes: 8,
    servings: 2,
    difficulty: "Easy",
    nutritionPerServing: {
      calories: 340,
      proteinG: 14,
      carbsG: 28,
      fatG: 20,
      fiberG: 8,
      sugarG: 2,
      sodiumMg: 380,
    },
    isFavorite: false,
    rating: 0,
    notes: "",
    createdAt: new Date("2026-01-10").toISOString(),
  },
  {
    id: "recipe-4",
    title: "Beef Tacos with Pico de Gallo",
    photoUrl: img("beef-tacos"),
    category: "Dinner",
    description: "Seasoned ground beef tacos topped with fresh homemade pico de gallo.",
    ingredients: [
      { id: "i1", name: "Ground Beef", quantity: 1, unit: "lb", category: "meat" },
      { id: "i2", name: "Corn Tortillas", quantity: 8, unit: "pieces", category: "pantry" },
      { id: "i3", name: "Tomato", quantity: 2, unit: "whole", category: "produce" },
      { id: "i4", name: "White Onion", quantity: 0.5, unit: "whole", category: "produce" },
      { id: "i5", name: "Cilantro", quantity: 0.25, unit: "cup", category: "produce" },
      { id: "i6", name: "Lime", quantity: 1, unit: "whole", category: "produce" },
      { id: "i7", name: "Cumin", quantity: 1, unit: "tsp", category: "spices" },
      { id: "i8", name: "Chili Powder", quantity: 1, unit: "tsp", category: "spices" },
      { id: "i9", name: "Shredded Cheddar", quantity: 1, unit: "cup", category: "dairy" },
    ],
    steps: [
      "Brown the ground beef in a skillet over medium-high heat, breaking it up as it cooks.",
      "Season with cumin, chili powder, and salt; cook until fully browned, about 8 minutes.",
      "Dice the tomato and onion, chop cilantro, and combine with lime juice to make the pico de gallo.",
      "Warm the corn tortillas in a dry skillet or over an open flame.",
      "Fill each tortilla with seasoned beef, top with pico de gallo and shredded cheddar.",
    ],
    tags: ["mexican", "spicy", "quick"],
    prepTimeMinutes: 15,
    cookTimeMinutes: 10,
    servings: 4,
    difficulty: "Easy",
    nutritionPerServing: {
      calories: 420,
      proteinG: 26,
      carbsG: 30,
      fatG: 22,
      fiberG: 4,
      sugarG: 3,
      sodiumMg: 510,
    },
    isFavorite: false,
    rating: 0,
    notes: "",
    createdAt: new Date("2026-01-12").toISOString(),
  },
  {
    id: "recipe-5",
    title: "Thai Green Curry with Vegetables",
    photoUrl: img("green-curry"),
    category: "Dinner",
    description: "A fragrant, spicy Thai curry loaded with fresh vegetables and coconut milk.",
    ingredients: [
      { id: "i1", name: "Coconut Milk", quantity: 2, unit: "cup", category: "pantry" },
      { id: "i2", name: "Green Curry Paste", quantity: 3, unit: "tbsp", category: "pantry" },
      { id: "i3", name: "Bell Pepper", quantity: 1, unit: "whole", category: "produce" },
      { id: "i4", name: "Zucchini", quantity: 1, unit: "whole", category: "produce" },
      { id: "i5", name: "Bamboo Shoots", quantity: 1, unit: "cup", category: "pantry" },
      { id: "i6", name: "Thai Basil", quantity: 0.5, unit: "cup", category: "produce" },
      { id: "i7", name: "Fish Sauce", quantity: 1, unit: "tbsp", category: "pantry" },
      { id: "i8", name: "Jasmine Rice", quantity: 2, unit: "cup", category: "pantry" },
    ],
    steps: [
      "Cook jasmine rice according to package instructions.",
      "In a pot, heat a spoonful of coconut milk and fry the green curry paste for 1-2 minutes until fragrant.",
      "Add the remaining coconut milk and bring to a gentle simmer.",
      "Add sliced bell pepper, zucchini, and bamboo shoots; simmer for 10 minutes until vegetables are tender.",
      "Stir in fish sauce and Thai basil leaves.",
      "Serve hot over jasmine rice.",
    ],
    tags: ["thai", "vegetarian-friendly", "spicy"],
    prepTimeMinutes: 15,
    cookTimeMinutes: 20,
    servings: 4,
    difficulty: "Medium",
    nutritionPerServing: {
      calories: 390,
      proteinG: 8,
      carbsG: 48,
      fatG: 18,
      fiberG: 4,
      sugarG: 6,
      sodiumMg: 600,
    },
    isFavorite: false,
    rating: 0,
    notes: "",
    createdAt: new Date("2026-01-14").toISOString(),
  },
  {
    id: "recipe-6",
    title: "Classic Caesar Salad",
    photoUrl: img("caesar-salad"),
    category: "Salad",
    description: "Crisp romaine lettuce tossed in a creamy homemade Caesar dressing with croutons and parmesan.",
    ingredients: [
      { id: "i1", name: "Romaine Lettuce", quantity: 2, unit: "heads", category: "produce" },
      { id: "i2", name: "Parmesan Cheese", quantity: 0.5, unit: "cup", category: "dairy" },
      { id: "i3", name: "Croutons", quantity: 1, unit: "cup", category: "pantry" },
      { id: "i4", name: "Mayonnaise", quantity: 0.5, unit: "cup", category: "pantry" },
      { id: "i5", name: "Anchovy Paste", quantity: 1, unit: "tsp", category: "pantry" },
      { id: "i6", name: "Garlic", quantity: 1, unit: "clove", category: "produce" },
      { id: "i7", name: "Lemon Juice", quantity: 2, unit: "tbsp", category: "produce" },
    ],
    steps: [
      "Chop the romaine lettuce into bite-sized pieces and place in a large bowl.",
      "Whisk together mayonnaise, anchovy paste, minced garlic, lemon juice, and half the parmesan for the dressing.",
      "Toss the lettuce with the dressing until evenly coated.",
      "Top with croutons and remaining parmesan cheese before serving.",
    ],
    tags: ["salad", "quick"],
    prepTimeMinutes: 15,
    cookTimeMinutes: 0,
    servings: 4,
    difficulty: "Easy",
    nutritionPerServing: {
      calories: 260,
      proteinG: 7,
      carbsG: 12,
      fatG: 21,
      fiberG: 3,
      sugarG: 2,
      sodiumMg: 480,
    },
    isFavorite: false,
    rating: 0,
    notes: "",
    createdAt: new Date("2026-01-16").toISOString(),
  },
  {
    id: "recipe-7",
    title: "Hearty Lentil Soup",
    photoUrl: img("lentil-soup"),
    category: "Soup",
    description: "A warming, hearty soup packed with lentils, vegetables, and warm spices.",
    ingredients: [
      { id: "i1", name: "Green Lentils", quantity: 1.5, unit: "cup", category: "pantry" },
      { id: "i2", name: "Carrot", quantity: 2, unit: "whole", category: "produce" },
      { id: "i3", name: "Celery", quantity: 2, unit: "stalks", category: "produce" },
      { id: "i4", name: "Yellow Onion", quantity: 1, unit: "whole", category: "produce" },
      { id: "i5", name: "Vegetable Broth", quantity: 6, unit: "cup", category: "pantry" },
      { id: "i6", name: "Cumin", quantity: 1, unit: "tsp", category: "spices" },
      { id: "i7", name: "Turmeric", quantity: 0.5, unit: "tsp", category: "spices" },
      { id: "i8", name: "Olive Oil", quantity: 2, unit: "tbsp", category: "pantry" },
    ],
    steps: [
      "Heat olive oil in a large pot and sauté diced onion, carrot, and celery until softened, about 6 minutes.",
      "Stir in cumin and turmeric and cook for 1 minute until fragrant.",
      "Add lentils and vegetable broth, bring to a boil, then reduce heat and simmer for 30 minutes.",
      "Season with salt and pepper to taste.",
      "Blend a portion of the soup for a creamier texture if desired, then serve hot.",
    ],
    tags: ["vegan", "soup", "healthy"],
    prepTimeMinutes: 10,
    cookTimeMinutes: 35,
    servings: 6,
    difficulty: "Easy",
    nutritionPerServing: {
      calories: 210,
      proteinG: 12,
      carbsG: 34,
      fatG: 4,
      fiberG: 10,
      sugarG: 4,
      sodiumMg: 390,
    },
    isFavorite: false,
    rating: 0,
    notes: "",
    createdAt: new Date("2026-01-18").toISOString(),
  },
  {
    id: "recipe-8",
    title: "Chocolate Chip Cookies",
    photoUrl: img("choc-chip-cookies"),
    category: "Dessert",
    description: "Soft, chewy chocolate chip cookies with crisp golden edges.",
    ingredients: [
      { id: "i1", name: "All-Purpose Flour", quantity: 2.25, unit: "cup", category: "pantry" },
      { id: "i2", name: "Butter", quantity: 1, unit: "cup", category: "dairy" },
      { id: "i3", name: "Brown Sugar", quantity: 0.75, unit: "cup", category: "pantry" },
      { id: "i4", name: "White Sugar", quantity: 0.75, unit: "cup", category: "pantry" },
      { id: "i5", name: "Eggs", quantity: 2, unit: "whole", category: "dairy" },
      { id: "i6", name: "Vanilla Extract", quantity: 1, unit: "tsp", category: "pantry" },
      { id: "i7", name: "Baking Soda", quantity: 1, unit: "tsp", category: "pantry" },
      { id: "i8", name: "Chocolate Chips", quantity: 2, unit: "cup", category: "pantry" },
      { id: "i9", name: "Salt", quantity: 1, unit: "tsp", category: "spices" },
    ],
    steps: [
      "Preheat oven to 375°F (190°C) and line baking sheets with parchment paper.",
      "Cream together butter, brown sugar, and white sugar until light and fluffy.",
      "Beat in eggs one at a time, then stir in vanilla extract.",
      "In a separate bowl, whisk together flour, baking soda, and salt, then gradually mix into the wet ingredients.",
      "Fold in chocolate chips.",
      "Drop rounded tablespoons of dough onto baking sheets, spaced 2 inches apart.",
      "Bake for 9-11 minutes until edges are golden. Cool on the sheet for 5 minutes before transferring.",
    ],
    tags: ["dessert", "baking", "vegetarian"],
    prepTimeMinutes: 15,
    cookTimeMinutes: 10,
    servings: 24,
    difficulty: "Easy",
    nutritionPerServing: {
      calories: 150,
      proteinG: 2,
      carbsG: 20,
      fatG: 7,
      fiberG: 1,
      sugarG: 13,
      sodiumMg: 90,
    },
    isFavorite: false,
    rating: 0,
    notes: "",
    createdAt: new Date("2026-01-20").toISOString(),
  },
  {
    id: "recipe-9",
    title: "Grilled Salmon with Lemon Butter",
    photoUrl: img("grilled-salmon"),
    category: "Dinner",
    description: "Flaky grilled salmon fillets finished with a bright lemon butter sauce.",
    ingredients: [
      { id: "i1", name: "Salmon Fillet", quantity: 4, unit: "pieces", category: "meat" },
      { id: "i2", name: "Butter", quantity: 4, unit: "tbsp", category: "dairy" },
      { id: "i3", name: "Lemon", quantity: 2, unit: "whole", category: "produce" },
      { id: "i4", name: "Garlic", quantity: 2, unit: "cloves", category: "produce" },
      { id: "i5", name: "Fresh Dill", quantity: 2, unit: "tbsp", category: "produce" },
      { id: "i6", name: "Salt", quantity: 1, unit: "tsp", category: "spices" },
      { id: "i7", name: "Black Pepper", quantity: 0.5, unit: "tsp", category: "spices" },
    ],
    steps: [
      "Preheat grill to medium-high heat and lightly oil the grates.",
      "Season salmon fillets with salt and pepper on both sides.",
      "Grill salmon skin-side down for 5-6 minutes, then flip and cook for another 3-4 minutes until flaky.",
      "Meanwhile, melt butter in a small saucepan, add minced garlic and lemon juice, and simmer for 2 minutes.",
      "Plate the salmon and spoon the lemon butter sauce over the top.",
      "Garnish with fresh dill and lemon wedges.",
    ],
    tags: ["seafood", "healthy", "grilling"],
    prepTimeMinutes: 10,
    cookTimeMinutes: 12,
    servings: 4,
    difficulty: "Medium",
    nutritionPerServing: {
      calories: 380,
      proteinG: 34,
      carbsG: 3,
      fatG: 26,
      fiberG: 0,
      sugarG: 1,
      sodiumMg: 420,
    },
    isFavorite: false,
    rating: 0,
    notes: "",
    createdAt: new Date("2026-01-22").toISOString(),
  },
  {
    id: "recipe-10",
    title: "Veggie Stir Fry with Tofu",
    photoUrl: img("veggie-stirfry"),
    category: "Dinner",
    description: "A colorful, quick weeknight stir fry with crispy tofu and a savory garlic-ginger sauce.",
    ingredients: [
      { id: "i1", name: "Firm Tofu", quantity: 14, unit: "oz", category: "other" },
      { id: "i2", name: "Broccoli Florets", quantity: 2, unit: "cup", category: "produce" },
      { id: "i3", name: "Carrot", quantity: 1, unit: "whole", category: "produce" },
      { id: "i4", name: "Bell Pepper", quantity: 1, unit: "whole", category: "produce" },
      { id: "i5", name: "Soy Sauce", quantity: 3, unit: "tbsp", category: "pantry" },
      { id: "i6", name: "Ginger", quantity: 1, unit: "tbsp", category: "produce" },
      { id: "i7", name: "Garlic", quantity: 2, unit: "cloves", category: "produce" },
      { id: "i8", name: "Sesame Oil", quantity: 1, unit: "tbsp", category: "pantry" },
      { id: "i9", name: "Jasmine Rice", quantity: 2, unit: "cup", category: "pantry" },
    ],
    steps: [
      "Press tofu to remove excess water, then cube and pan-fry in a hot skillet until golden on all sides. Set aside.",
      "Cook jasmine rice according to package instructions.",
      "In the same skillet, stir fry broccoli, carrot, and bell pepper over high heat for 4-5 minutes until crisp-tender.",
      "Add minced garlic and ginger, stir fry for 30 seconds until fragrant.",
      "Return tofu to the pan, add soy sauce and sesame oil, and toss everything together for 2 minutes.",
      "Serve hot over jasmine rice.",
    ],
    tags: ["vegan", "quick", "asian"],
    prepTimeMinutes: 15,
    cookTimeMinutes: 15,
    servings: 4,
    difficulty: "Easy",
    nutritionPerServing: {
      calories: 340,
      proteinG: 16,
      carbsG: 42,
      fatG: 12,
      fiberG: 5,
      sugarG: 5,
      sodiumMg: 620,
    },
    isFavorite: false,
    rating: 0,
    notes: "",
    createdAt: new Date("2026-01-24").toISOString(),
  },
  {
    id: "recipe-11",
    title: "Blueberry Pancakes",
    photoUrl: img("blueberry-pancakes"),
    category: "Breakfast",
    description: "Fluffy buttermilk pancakes bursting with fresh blueberries.",
    ingredients: [
      { id: "i1", name: "All-Purpose Flour", quantity: 2, unit: "cup", category: "pantry" },
      { id: "i2", name: "Buttermilk", quantity: 1.75, unit: "cup", category: "dairy" },
      { id: "i3", name: "Eggs", quantity: 2, unit: "whole", category: "dairy" },
      { id: "i4", name: "Blueberries", quantity: 1, unit: "cup", category: "produce" },
      { id: "i5", name: "Sugar", quantity: 2, unit: "tbsp", category: "pantry" },
      { id: "i6", name: "Baking Powder", quantity: 2, unit: "tsp", category: "pantry" },
      { id: "i7", name: "Butter", quantity: 3, unit: "tbsp", category: "dairy" },
      { id: "i8", name: "Salt", quantity: 0.5, unit: "tsp", category: "spices" },
    ],
    steps: [
      "Whisk together flour, sugar, baking powder, and salt in a large bowl.",
      "In a separate bowl, whisk buttermilk, eggs, and melted butter.",
      "Combine wet and dry ingredients, stirring just until incorporated (a few lumps are fine).",
      "Gently fold in the blueberries.",
      "Heat a griddle over medium heat and pour 1/4 cup of batter per pancake.",
      "Cook until bubbles form on the surface, flip, and cook until golden on the other side.",
      "Serve warm with maple syrup.",
    ],
    tags: ["breakfast", "baking", "vegetarian"],
    prepTimeMinutes: 10,
    cookTimeMinutes: 15,
    servings: 4,
    difficulty: "Easy",
    nutritionPerServing: {
      calories: 310,
      proteinG: 9,
      carbsG: 48,
      fatG: 9,
      fiberG: 2,
      sugarG: 12,
      sodiumMg: 380,
    },
    isFavorite: false,
    rating: 0,
    notes: "",
    createdAt: new Date("2026-01-26").toISOString(),
  },
  {
    id: "recipe-12",
    title: "Roasted Vegetable Buddha Bowl",
    photoUrl: img("buddha-bowl"),
    category: "Lunch",
    description: "A nourishing bowl of roasted vegetables, quinoa, and a creamy tahini dressing.",
    ingredients: [
      { id: "i1", name: "Quinoa", quantity: 1, unit: "cup", category: "pantry" },
      { id: "i2", name: "Sweet Potato", quantity: 1, unit: "whole", category: "produce" },
      { id: "i3", name: "Chickpeas", quantity: 1, unit: "can", category: "pantry" },
      { id: "i4", name: "Kale", quantity: 2, unit: "cup", category: "produce" },
      { id: "i5", name: "Tahini", quantity: 3, unit: "tbsp", category: "pantry" },
      { id: "i6", name: "Lemon Juice", quantity: 2, unit: "tbsp", category: "produce" },
      { id: "i7", name: "Olive Oil", quantity: 2, unit: "tbsp", category: "pantry" },
      { id: "i8", name: "Cumin", quantity: 1, unit: "tsp", category: "spices" },
    ],
    steps: [
      "Preheat oven to 400°F (200°C). Cook quinoa according to package instructions.",
      "Cube sweet potato and toss with olive oil, cumin, and salt. Roast for 25 minutes until tender.",
      "Drain and rinse chickpeas, toss with a little oil, and roast alongside the sweet potato for the last 15 minutes.",
      "Massage kale with a pinch of salt and a squeeze of lemon juice to soften.",
      "Whisk tahini with lemon juice and a splash of water until pourable for the dressing.",
      "Assemble bowls with quinoa, roasted sweet potato, chickpeas, and kale, then drizzle with tahini dressing.",
    ],
    tags: ["vegan", "healthy", "meal-prep"],
    prepTimeMinutes: 15,
    cookTimeMinutes: 30,
    servings: 4,
    difficulty: "Easy",
    nutritionPerServing: {
      calories: 410,
      proteinG: 13,
      carbsG: 58,
      fatG: 15,
      fiberG: 11,
      sugarG: 6,
      sodiumMg: 340,
    },
    isFavorite: false,
    rating: 0,
    notes: "",
    createdAt: new Date("2026-01-28").toISOString(),
  },
];
